#################################################################################
# Dozzle: Docker log viewer.                                                  #
# https://dozzle.dev/                                                         #
#################################################################################

---
services:
  dozzle:
    image: ghcr.io/amir20/dozzle:v8
    container_name: dozzle
    env_file: ../../.env
    hostname: dozzle
    read_only: true
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    environment:
      DOCKER_HOST: "tcp://socket-proxy:2375" # Connects to the socket proxy.
      DOZZLE_ENABLE_ACTIONS: "true" # Enables container actions.
      DOZZLE_ENABLE_SHELL: "true" # Enables entering container shells.
    expose:
      - 8080/tcp
    networks:
      - external
      - internal
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - dozzle:/data
    cap_drop:
      - ALL
    depends_on:
      socket-proxy:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 256M
    healthcheck:
      interval: 1m
      test: "./dozzle healthcheck || exit 1"
      timeout: 5s
    security_opt:
      - no-new-privileges:true

networks:
  external:
    external: true
    name: external-network
  internal:
    external: true
    name: internal-network

volumes:
  dozzle:
    name: dozzle-volume
    external: true
