# Autobrr: Download automation tool and ratio manager.
# https://autobrr.com/introduction

---
x-defaults: &defaults
  read_only: true
  restart: unless-stopped
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges:true

services:
  autobrr:
    <<: *defaults
    image: ghcr.io/s0up4200/autobrr-distroless:v1.72
    container_name: autobrr
    network_mode: service:gluetun
    user: "${PUID}:${PGID}"
    environment:
      AUTOBRR__DATABASE_TYPE: "postgres"
      AUTOBRR__POSTGRES_DATABASE: "postgres"
      AUTOBRR__POSTGRES_HOST: "autobrr-db"
      AUTOBRR__POSTGRES_PASS: "${AUTOBRR_DB_PASSWORD}"
      AUTOBRR__POSTGRES_PORT: "5432"
      AUTOBRR__POSTGRES_USER: "postgres"
    tmpfs:
      - "/tmp:uid=${PUID},gid=${PGID}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - autobrr:/config:rw
    depends_on:
      autobrr-db:
        condition: service_healthy
        restart: true
      gluetun:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G

  autobrr-db:
    <<: *defaults
    image: ghcr.io/11notes/postgres:18
    container_name: autobrr-db
    shm_size: 256MB
    environment:
      POSTGRES_PASSWORD: "${AUTOBRR_DB_PASSWORD}"
      TZ: "${TZ}"
    networks:
      - gluetun
    tmpfs:
      - "/postgres/log:uid=1000,gid=1000"
      - "/postgres/run:uid=1000,gid=1000"
    volumes:
      - autobrr-db-config:/postgres/etc:rw
      - autobrr-db-data:/postgres/var:rw
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 512M

networks:
  gluetun:
    name: gluetun-network
    external: true
  internal:
    name: internal-network
    external: true

volumes:
  autobrr:
    name: autobrr-volume
    external: true
  autobrr-db-config:
    name: autobrr-db-config-volume
    external: true
  autobrr-db-data:
    name: autobrr-db-data-volume
    external: true
