#################################################################################
# Autobrr: Download automation tool and ratio manager.                        #
# https://autobrr.com/introduction                                            #
#################################################################################

---
x-defaults: &defaults
  env_file: ../../.env
  read_only: true
  restart: unless-stopped
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges:true

services:
  autobrr:
    <<: *defaults
    image: ghcr.io/autobrr/autobrr:v1.70
    container_name: autobrr
    network_mode: service:gluetun
    user: "${PUID}:${PGID}"
    environment:
      AUTOBRR__CHECK_FOR_UPDATES: "false" # Do not check for updates.
      AUTOBRR__DATABASE_TYPE: "postgres" # Use PostgreSQL.
      AUTOBRR__HOST: "0.0.0.0" # Bind to 0.0.0.0.
      AUTOBRR__LOG_LEVEL: "info" # Log at the info level.
      AUTOBRR__LOG_MAX_SIZE: "10" # Keep log files until they reach 10mb.
      AUTOBRR__LOG_PATH: "/logs/autobrr.log" # Sets the log file path.
      AUTOBRR__POSTGRES_DATABASE: "postgres" # Use the Postgres database.
      AUTOBRR__POSTGRES_HOST: "172.19.1.31" # Connect to the Gluetun-network'd database.
      AUTOBRR__POSTGRES_PASS: "${AUTOBRR_DB_PASSWORD}" # Database password to authenticate with.
      AUTOBRR__POSTGRES_PORT: "5432" # Connect to port 5432.
      AUTOBRR__POSTGRES_USER: "postgres" # Use the postgres user.
      TZ: "${TZ}" # Sets the timezone.
    tmpfs:
      - "/tmp:mode=1777,uid=${PUID},gid=${PGID}"
    volumes:
      - autobrr-data:/config
      - autobrr-logs:/logs
    depends_on:
      autobrr-db:
        condition: service_healthy
        restart: true
      gluetun:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
    healthcheck:
      interval: 1m
      test: "curl --fail --retry 0 --silent http://127.0.0.1:7474 || exit 1"
      timeout: 5s

  autobrr-db:
    <<: *defaults
    image: ghcr.io/11notes/postgres:18
    container_name: autobrr-db
    shm_size: 256MB
    environment:
      POSTGRES_PASSWORD: "${AUTOBRR_DB_PASSWORD}" # Sets the password.
      TZ: "${TZ}" # Sets the timezone.
    networks:
      gluetun:
        ipv4_address: 172.19.1.31
    tmpfs:
      - "/postgres/log:mode=1777,uid=${PUID},gid=${PGID}"
      - "/postgres/run:mode=1777,uid=${PUID},gid=${PGID}"
    volumes:
      - autobrr-db-config:/postgres/etc
      - autobrr-db-data:/postgres/var
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 256M

networks:
  gluetun:
    name: gluetun-network
    external: true
  internal:
    name: internal-network
    external: true

volumes:
  autobrr-data:
    name: autobrr-data-volume
    external: true
  autobrr-logs:
    name: autobrr-logs-volume
    external: true
  autobrr-db-config:
    name: autobrr-db-config-volume
    external: true
  autobrr-db-data:
    name: autobrr-db-data-volume
    external: true
