###############################################################################
# Autobrr: Download automation tool and ratio manager.                        #
# https://autobrr.com/introduction                                            #
###############################################################################

---
x-defaults: &defaults
  env_file: ../../.env
  read_only: true
  restart: unless-stopped
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges:true

services:
  autobrr:
    <<: *defaults
    image: ghcr.io/s0up4200/autobrr-distroless:v1.71.0
    container_name: autobrr
    network_mode: service:gluetun
    user: "${PUID}:${PGID}"
    environment:
      AUTOBRR__DATABASE_TYPE: "postgres" # Use PostgreSQL.
      AUTOBRR__POSTGRES_DATABASE: "postgres" # Use the Postgres database.
      AUTOBRR__POSTGRES_HOST: "autobrr-db" # Connect to the database.
      AUTOBRR__POSTGRES_PASS: "${AUTOBRR_DB_PASSWORD}" # Database password to authenticate with.
      AUTOBRR__POSTGRES_PORT: "5432" # Connect to port 5432.
      AUTOBRR__POSTGRES_USER: "postgres" # Use the postgres user.
    tmpfs:
      - "/tmp:uid=${PUID},gid=${PGID}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - autobrr:/config:rw
    depends_on:
      autobrr-db:
        condition: service_healthy
        restart: true
      gluetun:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
        reservations:
          cpus: 0.25
          memory: 128M
    healthcheck:
      test: "curl --fail --retry 0 --silent http://127.0.0.1:7474 || exit 1"

  autobrr-db:
    <<: *defaults
    image: ghcr.io/11notes/postgres:18
    container_name: autobrr-db
    shm_size: 256MB
    environment:
      POSTGRES_PASSWORD: "${AUTOBRR_DB_PASSWORD}" # Sets the password.
      TZ: "${TZ}" # Sets the timezone.
    networks:
      - gluetun
    tmpfs:
      - "/postgres/log:uid=1000,gid=1000"
      - "/postgres/run:uid=1000,gid=1000"
    volumes:
      - autobrr-db-config:/postgres/etc:rw
      - autobrr-db-data:/postgres/var:rw
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 256M
        reservations:
          cpus: 0.15
          memory: 64M

networks:
  gluetun:
    name: gluetun-network
    external: true
  internal:
    name: internal-network
    external: true

volumes:
  autobrr:
    name: autobrr-volume
    external: true
  autobrr-db-config:
    name: autobrr-db-config-volume
    external: true
  autobrr-db-data:
    name: autobrr-db-data-volume
    external: true
