###############################################################################
# Kavita: eBook/Comic/Manga media server.                                     #
# https://wiki.kavitareader.com/                                              #
###############################################################################

---
services:
  kavita:
    image: ghcr.io/kareadita/kavita:0.8.8
    container_name: kavita
    env_file: ../../.env
    hostname: kavita
    restart: unless-stopped
    read_only: true
    user: "${PUID}:${PGID}"
    environment:
      TZ: "${TZ}" # Sets the timezone.
    expose:
      - 5000/tcp
    networks:
      - external
    tmpfs:
      - "/tmp:uid=${PUID},gid=${PGID}"
    volumes:
      - kavita:/kavita/config:rw
      - media-library:/library:ro
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
        reservations:
          cpus: 0.25
          memory: 256MB
    healthcheck:
      test: "curl --fail --retry 0 --silent http://127.0.0.1:5000 || exit 1"
    security_opt:
      - no-new-privileges:true

networks:
  external:
    external: true
    name: external-network

volumes:
  kavita:
    external: true
    name: kavita-volume
  media-library:
    name: media-library-bind
    driver_opts:
      device: "${MEDIA_LIBRARY_PATH}"
      o: bind
      type: none
