# The Lounge: Web-based IRC client.
# https://github.com/thelounge/thelounge-docker

---
services:
  thelounge:
    image: ghcr.io/thelounge/thelounge:4
    container_name: thelounge
    env_file: ../../.env
    hostname: thelounge
    read_only: true
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    expose:
      - 9000/tcp
    networks:
      - external
    tmpfs:
      - "/tmp:uid=${PUID},gid=${PGID}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - thelounge:/var/opt/thelounge:rw
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 512M
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://127.0.0.1:9000 || exit 1"
    security_opt:
      - no-new-privileges:true

networks:
  external:
    external: true
    name: external-network

volumes:
  thelounge:
    external: true
    name: thelounge-volume
