###########################################################################
# The Lounge: Web-based IRC client - https://thelounge.chat               #
###########################################################################

---
services:
  thelounge:
    image: ghcr.io/thelounge/thelounge:4
    container_name: thelounge
    hostname: thelounge
    read_only: true # Prevent writing directly to the image.
    restart: unless-stopped
    user: "${PUID}:${PGID}" # Run as non-root user.
    environment:
      TZ: "${TZ}" # Sets the timezone.
    networks:
      - external
    expose:
      - 9000/tcp # Web interface reverse proxied externally at ${THELOUNGE_URL}.
    tmpfs:
      - "/tmp:uid=${PUID},gid=${PGID}" # Required for read_only image.
    volumes:
      - thelounge:/var/opt/thelounge # Configuration and data.
    cap_drop:
      - ALL # Drop all default capabilities.
    deploy:
      resources:
        limits:
          cpus: 0.5 # Allow up to 1 vCPU.
          memory: 256M # Allow up to 512MB of RAM.
        reservations:
          cpus: 0.25 # Reserve 0.25 vCPUs.
          memory: 128M # Reserve 128MB of RAM.
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://127.0.0.1:9000 || exit 1"
    security_opt:
      - no-new-privileges:true # Do not allow privilege escalation.

networks:
  external:
    external: true
    name: external-network

volumes:
  thelounge:
    external: true
    name: thelounge-volume
