# Prowlarr: Indexer manager and synchronization for 'ARR apps.
# https://prowlarr.com/

---
x-defaults: &defaults
  env_file: ../../.env
  read_only: true
  restart: unless-stopped
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges:true

services:
  prowlarr:
    <<: *defaults
    image: ghcr.io/11notes/prowlarr:2
    container_name: prowlarr
    network_mode: service:gluetun
    environment:
      TZ: "${TZ}" # Sets the timezone.
    volumes:
      - prowlarr:/prowlarr/etc:rw
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
      prowlarr-db:
        condition: service_healthy
        restart: true
    tmpfs:
      - "/tmp:uid=1000,gid=1000"
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G

  prowlarr-db:
    <<: *defaults
    image: ghcr.io/11notes/postgres:18
    container_name: prowlarr-db
    hostname: prowlarr-db
    shm_size: 256MB
    environment:
      TZ: "${TZ}" # Sets the timezone.
      POSTGRES_PASSWORD: "${PROWLARR_DB_PASSWORD}" # Sets the database password.
    networks:
      - gluetun
    tmpfs:
      - "/postgres/log:uid=1000,gid=1000"
      - "/postgres/run:uid=1000,gid=1000"
    volumes:
      - prowlarr-db-config:/postgres/etc:rw
      - prowlarr-db-data:/postgres/var:rw
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G

networks:
  gluetun:
    external: true
    name: gluetun-network

volumes:
  prowlarr:
    name: prowlarr-volume
    external: true
  prowlarr-db-config:
    name: prowlarr-db-config-volume
    external: true
  prowlarr-db-data:
    name: prowlarr-db-data-volume
    external: true
