#################################################################################
# Homarr: Dashboard and homepage.                                             #
# https://homarr.dev/docs/getting-started/installation/docker/                #
#################################################################################

---
x-defaults: &defaults
  env_file: ../../.env
  restart: unless-stopped
  security_opt:
    - no-new-privileges:true

services:
  homarr:
    <<: *defaults
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    hostname: homarr
    environment:
      DB_URL: "postgres://postgres:${HOMARR_DB_PASSWORD}@homarr-db:5432/postgres" # Connect to PostgreSQL.
      DB_DIALECT: "postgresql" # Use PostgreSQL.
      DB_DRIVER: "node-postgres" # Use PostgreSQL database driver.
      DOCKER_HOSTNAMES: "socket-proxy" # Connect to the socket-proxy host.
      DOCKER_PORTS: "2375" # Connect to the socket-proxy port.
      PGID: "${PGID}" # Group ID to run as.
      PUID: "${PUID}" # User ID to run as.
      SECRET_ENCRYPTION_KEY: "${HOMARR_ENCRYPTION_KEY}" # openssl rand -hex 32
      TZ: "${TZ}" # Sets the timezone.
    expose:
      - 7575/tcp
    networks:
      - external
      - gluetun
      - internal
    volumes:
      - homarr:/appdata
    cap_drop:
      - AUDIT_WRITE
      - MKNOD
      - SETFCAP
      - SETPCAP
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    depends_on:
      homarr-db:
        condition: service_healthy
        restart: true
      socket-proxy:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
    healthcheck:
      interval: 1m
      test: "wget --no-verbose --tries=1 --spider http://127.0.0.1:7575 || exit 1"
      timeout: 5s

  homarr-db:
    <<: *defaults
    image: ghcr.io/11notes/postgres:18
    container_name: homarr-db
    hostname: homarr-db
    read_only: true
    shm_size: 256MB
    environment:
      POSTGRES_PASSWORD: "${HOMARR_DB_PASSWORD}" # Sets the password.
      TZ: "${TZ}" # Timezone to set.
    networks:
      - internal
    tmpfs:
      - "/postgres/log:mode=1777,uid=${PUID},gid=${PGID}"
      - "/postgres/run:mode=1777,uid=${PUID},gid=${PGID}"
    volumes:
      - homarr-db-config:/postgres/etc
      - homarr-db-data:/postgres/var
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 256M

networks:
  external:
    external: true
    name: external-network
  gluetun:
    external: true
    name: gluetun-network
  internal:
    external: true
    name: internal-network

volumes:
  homarr:
    name: homarr-volume
    external: true
  homarr-db-data:
    name: homarr-db-data-volume
    external: true
  homarr-db-config:
    name: homarr-db-config-volume
    external: true
