###########################################################################
# Homarr: Dashboard and homepage - https://homarr.dev/                    #
###########################################################################

---
x-defaults: &defaults
  restart: unless-stopped
  security_opt:
    - no-new-privileges:true

services:
  homarr:
    <<: *defaults
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    hostname: homarr
    environment:
      DB_DIALECT: "postgresql"
      DB_DRIVER: "node-postgres"
      DB_HOST: "homarr-db"
      DB_NAME: "postgres"
      DB_PASSWORD: "${HOMARR_DB_PASSWORD}"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DOCKER_HOSTNAMES: "socket-proxy"
      DOCKER_PORTS: "2375"
      PGID: "${PGID}"
      PUID: "${PUID}"
      SECRET_ENCRYPTION_KEY: "${HOMARR_ENCRYPTION_KEY}"
      TZ: "${TZ}"
    expose:
      - 7575/tcp
    networks:
      - external
      - gluetun
      - internal
    volumes:
      - homarr:/appdata
    cap_drop:
      - AUDIT_WRITE
      - MKNOD
      - SETFCAP
      - SETPCAP
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    depends_on:
      homarr-db:
        condition: service_healthy
        restart: true
      socket-proxy:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2G
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://127.0.0.1:7575 || exit 1"

  homarr-db:
    <<: *defaults
    image: ghcr.io/11notes/postgres:18
    container_name: homarr-db
    hostname: homarr-db
    read_only: true
    environment:
      POSTGRES_PASSWORD: "${HOMARR_DB_PASSWORD}"
      TZ: "${TZ}"
    networks:
      - internal
    tmpfs:
      - "/postgres/log:uid=${PUID},gid=${PGID}"
      - "/postgres/run:uid=${PUID},gid=${PGID}"
    volumes:
      - homarr-db-config:/postgres/etc
      - homarr-db-data:/postgres/var
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 256M

networks:
  external:
    external: true
    name: external-network
  gluetun:
    external: true
    name: gluetun-network
  internal:
    external: true
    name: internal-network

volumes:
  homarr:
    name: homarr-volume
    external: true
  homarr-db-data:
    name: homarr-db-data-volume
    external: true
  homarr-db-config:
    name: homarr-db-config-volume
    external: true
  homarr-db-backups:
    name: homarr-db-backups-volume
    external: true
