# Chhoto URL: URL forwarder and shortener.
# https://github.com/sintan1729/chhoto-url

---
services:
  chhoto:
    image: ghcr.io/sintan1729/chhoto-url:6.5-alpine
    container_name: chhoto
    hostname: chhoto
    read_only: true
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    environment:
      api_key: "${CHHOTO_API_KEY}" # openssl rand -hex 32
      db_url: "/db/urls.sqlite" # Store database in /db/urls.sqlite.
      ensure_acid: "True" # Ensures ACID compliance.
      password: "${CHHOTO_PASSWORD}" # Administrator password to set.
      site_url: https://${CHHOTO_URL} # URL to use.
      slug_style: "Pair" # Use paired slug styling.
      TZ: "${TZ}" # Sets the timezone.
      use_wal_mode: "True" # Use WAL mode for SQLite.
    expose:
      - 4567/tcp
    networks:
      - external
    volumes:
      - chhoto-data:/db:rw
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 256M
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://127.0.0.1:4567/api/whoami || exit 1"

networks:
  external:
    external: true
    name: external-network

volumes:
  chhoto-data:
    name: chhoto-data-bind
    driver_opts:
      device: "${APPDATA_PATH}/chhoto"
      o: bind
      type: none
