###########################################################################
# Chhoto URL: URL shortener - https://github.com/sintan1729/chhoto-url    #
###########################################################################

---
services:
  chhoto:
    image: ghcr.io/sintan1729/chhoto-url:6-alpine
    container_name: chhoto
    hostname: chhoto
    read_only: true
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    environment:
      api_key: "${CHHOTO_API_KEY}"
      db_url: "/db/urls.sqlite"
      ensure_acid: "True"
      password: "${CHHOTO_PASSWORD}"
      site_url: https://${CHHOTO_URL}
      slug_style: "Pair"
      TZ: "${TZ}"
      use_wal_mode: "True"
    expose:
      - 4567/tcp
    networks:
      - external
    volumes:
      - chhoto:/db
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 64M
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://127.0.0.1:4567/api/whoami || exit 1"

networks:
  external:
    external: true
    name: external-network

volumes:
  chhoto:
    name: chhoto-volume
    external: true
